### ISSUE TITLE
Recent modifications to code

### ISSUE THREAD

**Issue by onlynone** [authy/authy-java#20]
I noticed that my recent pull request #19 is no longer merge-able because of extensive refactoring of the code base. It looks like some of the things I added in my pull request were added to master, but in incompatible ways (eg: `Formattable`\* vs `Request`; and the way alternate serializations/content-types are handled). The master branch also apparently underwent a massive whitespace change, which makes diffs even harder to apply.

It would be nice if there was discussion about how new features were going to be implemented. Also, if the code lags behind so far behind that users are having to go out of their way to implement the missing features, and they share their modifications back with the community, it would be nice if some deference were given to these initial implementations.

*doubly frustrating since [Formattable](http://docs.oracle.com/javase/7/docs/api/java/util/Formattable.html) is already a standard java interface

**Comment by moisesweb** [comment]
@onlynone I see what you did a great contribution with the PR #19 , I'm sorry my last PR make this no longer merge-able, I would like to see perhaps a rebase could work to merge this pull request. I thought `Formattable` as a good name for the `Response` interface since it only declare the implementation of different format representation of an object; but I see you went further with `Request abstract class` looks pretty neat.
